---
- name: Habilitar Flap-Guard nas interfaces
  hosts: fortiswitch48
  gather_facts: no

  tasks:
    - name: Configurar Flap-Guard
      ansible.builtin.raw: |
        config switch physical-port
        edit {{ port_id }}
        set flapguard enable
        set flap-rate {{ flap_rate }}
        set flap-duration {{ flap_duration }}
        set flap-timeout {{ flap_timeout }}
        next
        end
