- name: Criar VLAN e configurar IP
  hosts: fortiswitch48
  gather_facts: no

  tasks:
    - name: Configurar SVI
      ansible.builtin.raw: |
        config system interface
        edit USERS
        set vlanid 25
        set interface internal
        set ip 10.11.11.11 255.255.255.0
        set allowaccess ping http https ssh
        next
        end
