---
- name: Criar VLAN e configurar IP
  hosts: fortiswitch48
  gather_facts: no

  tasks:
    - name: Configurar SVI
      ansible.builtin.raw: |
        config system interface
        edit {{ vlan_name }}
        set vlanid {{ vlan_id }}
        set interface internal
        set ip {{ vlan_ip }} {{ vlan_netmask }}
        set allowaccess ping http https ssh
        next
        end
